data:
  raw_path: "data/raw/Walmart_data.csv"


models:

  random_forest:
    type: "RandomForestRegressor"
    params:
      n_estimators: 100
      max_depth: 10

  linear_regressor:
    type: "LinearRegression"
    params: {}

  XGBoost:
    type: "XGBoost"
    params:
      max_depth: 10

